---
title: "Data Visulization: Flights on ABIA"
author: Richard Marks
date: 2/10/2020
output: pdf_document
---
```{r setup, include=FALSE}
library(mosaic,)
library(tidyverse)
library(ggplot2)
knitr::opts_chunk$set(echo = FALSE)
```
```{r}
load("~/.Rdata")
Total_Flight_Delays = (ABIA %>% group_by(UniqueCarrier,Month) %>% summarize(Carrier_Delay = mean(CarrierDelay + WeatherDelay + NASDelay + SecurityDelay + LateAircraftDelay, na.rm = TRUE)))
```
```{r}
Total_Flight_Delays_Season=Total_Flight_Delays %>% mutate(Season= cut(Month,c(0,3,6,9,12)))
levels(Total_Flight_Delays_Season$Season)[levels(Total_Flight_Delays_Season$Season)=="(6,9]"]   <- "Summer"
levels(Total_Flight_Delays_Season$Season)[levels(Total_Flight_Delays_Season$Season)=="(9,12]"]   <- "Fall"
levels(Total_Flight_Delays_Season$Season)[levels(Total_Flight_Delays_Season$Season)=="(3,6]"]   <- "Spring"
levels(Total_Flight_Delays_Season$Season)[levels(Total_Flight_Delays_Season$Season)=="(0,3]"] <- "Winter"
```

```{r}
Total_Flight_Delays_Seasons=Total_Flight_Delays_Season %>% group_by(Season,UniqueCarrier) %>% summarize(mean(Carrier_Delay, na.rm = TRUE))
 Flight_Delays_Season= Total_Flight_Delays_Seasons %>% rename(Delays = `mean(Carrier_Delay, na.rm = TRUE)`)
```
```{r}
levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="AA"] <- "American Airlines"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="9E"] <- "Endeavor Air"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="B6"] <- "Jetblue Airways"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="CO"] <- "Continental Airlines"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="DL"] <- "Delta Airlines"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="EV"] <- "ExpressJet Airlines"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="F9"] <- "Frontier Airlines"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="MQ"] <- "Envoy Air"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="NW"] <- "Northwest Airlines"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="OH"] <- "US Airways Express"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="OO"] <- "SkyWest Airlines"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="UA"] <- "United Airlines"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="US"] <- "Puerto rico International Airlines"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="WN"] <- "SouthWest Airlines"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="XE"] <- "JSX Air"
 levels(Flight_Delays_Season$UniqueCarrier)[levels(Flight_Delays_Season$UniqueCarrier)=="YV"] <- "Mesa Airlines"
```


```{r}
ggplot(data = Flight_Delays_Season) + geom_bar(mapping = aes(x= reorder(UniqueCarrier,Delays), y= Delays), stat = 'identity') + coord_flip() + labs(x="Airline (Code)", y= "Average Delay Time (Minutes)", title = "Which Airlines Have the Longest Average Delays", subtitle = "For Each Season") + facet_wrap(~ Season, nrow = 2)
```


